# Спонсорство

github: nyafirawr
patreon: nyafirawr
custom:
  [
    'Никнейм на QIWI: NYAFIRAWR',
    'WebMoney WMR: R119858043867',
    'https://money.yandex.ru/to/410014841265118',
    'https://www.paypal.me/nyafiru',
  ]
