name: Проверка компиляции проекта

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Установка Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'
        
    - name: Установка зависимостей и компиляция проекта
      run: |
          npm install
          npm run lint
          npm run build